name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"

      - name: checkout repo content
        uses: actions/checkout@v2 
        
      - name: present working directory
        run: pwd
        
      - name: get files
        run: ls
          
